services:
  - type: web
    name: book-backend
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: |
      export PYTHONPATH=backend
      uvicorn api.main:app --host 0.0.0.0 --port $PORT



